### ISSUE TITLE
Consider adding support v1beta1 for backward compatibility

### ISSUE THREAD

**Issue by Dentrax** [postfinance/kubelet-csr-approver#216]
It'd be nice to add support for `v1beta1` API version. Currently project only works with `v1` version.

**Comment by clementnuss** [comment]
just to be sure, can you precise which API resource? the CSR itself ?

**Comment by clementnuss** [comment]
Certificate Signing Request is stable since Kubernetes v1.19 ([docs](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#certificate-signing-requests)).

sorry, I will not implement backward-compatibility, this is too far in the past. 

you can try using `kubelet-rubber-stamp`, which is old and might work with the API version you are referring to: https://github.com/kontena/kubelet-rubber-stamp
