### ISSUE TITLE
Error: INSTALLATION FAILED: failed parsing --set data: error parsing index: strconv.Atoi: parsing "0-5": invalid syntax

### ISSUE THREAD

**Issue by lovemianhuatang** [postfinance/kubelet-csr-approver#223]
~~~sh
helm install kubelet-csr-approver kubelet-csr-approver/kubelet-csr-approver -n kube-system \
  --set providerRegex='^cn-[a-z]+\.192\.168\.((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})\.((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})$' \
  --set providerIpPrefixes='192.168.0.0/16' \
  --set maxExpirationSeconds='86400'
~~~
return results: Error: INSTALLATION FAILED: failed parsing --set data: error parsing index: strconv.Atoi: parsing "0-5": invalid syntax

I want to match: cn-xxxxx.192.168.xxx.xxx

**Comment by clementnuss** [comment]
you regex seems correct, I think the issue here is that `helm --set` doesn't like receiving a regex as an argument. I tried changing the quotes, surrounding with double quotes, escaping backslashes, all without success.

at this point I'd suggest looking into helm's open issues, maybe someone is facing the same problem.
and otherwise I would suggest using values.yaml to configure the Chart. but then you'll need to escape the backslashes, as follows:
```yaml
providerRegex: "^cn-[a-z]+\\.192\\.168\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})$"
```

**Comment by lovemianhuatang** [comment]
OK, thanks for your reply.
