### ISSUE TITLE
Chart.yaml version, appVersion

### ISSUE THREAD

**Issue by ke5C2Fin** [postfinance/kubelet-csr-approver#224]
When pulling this chart from a Git Repo (for situations where a Helm Repo is not available), the Chart.yaml always shows `version` and `appVersion` as `0.0.1-dummy` instead of i.e. `1.0.7`

Could Chart.yaml be updated at release times to correctly state the version?

**Comment by clementnuss** [comment]
unfortunately not, because it made it quite tricky not to forget to update the `version`, `appVersion` fields when we made a tag. 

I had changed that and now the chart version is automatically to the tag, which makes sure we never forget to update it.

I would advise for using the dedicated helm chart repo, over here: https://postfinance.github.io/kubelet-csr-approver
